# Generated by Django 3.2.9 on 2021-11-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70)),
                ('desc', models.CharField(max_length=500)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PlacedOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default=0)),
                ('order_status', models.CharField(choices=[('u', 'Payment Not Done'), ('f', 'Payment Failed'), ('s', 'Success'), ('w', 'Payment withdrawn')], default='u', max_length=1)),
                ('items_ordered', models.CharField(max_length=100000)),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_desc', models.CharField(max_length=300)),
                ('product_image', models.ImageField(default='', upload_to='shop/image')),
                ('product_price', models.IntegerField(default=0)),
                ('product_category', models.CharField(default='', max_length=30)),
                ('product_subcategory', models.CharField(default='', max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
