# Generated by Django 3.2.9 on 2021-11-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedorder',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
