# Generated by Django 3.2.9 on 2021-11-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='', upload_to='shop/image'),
        ),
    ]
