# Generated by Django 3.2.9 on 2021-11-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('BANKNAME', models.CharField(max_length=20)),
                ('BANKTXNID', models.CharField(max_length=20)),
                ('CURRENCY', models.CharField(max_length=4)),
                ('GATEWAYNAME', models.CharField(max_length=20)),
                ('MID', models.CharField(max_length=30)),
                ('ORDERID', models.CharField(max_length=30)),
                ('PAYMENTMODE', models.CharField(max_length=10)),
                ('RESPCODE', models.CharField(max_length=10)),
                ('RESPMSG', models.CharField(max_length=200)),
                ('STATUS', models.CharField(max_length=10)),
                ('TXNAMOUNT', models.CharField(max_length=10)),
                ('TXNDATE', models.DateField()),
                ('TXNID', models.CharField(max_length=30)),
            ],
        ),
    ]
