# Generated by Django 3.2.9 on 2021-11-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0002_paymentdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='TXNDATE',
            field=models.DateTimeField(),
        ),
    ]
