# Generated by Django 3.2.9 on 2021-11-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacedOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('items_ordered', models.CharField(max_length=100000)),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
