# Generated by Django 3.2.9 on 2021-11-21 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0003_alter_paymentdetails_txndate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentDetails',
            new_name='PaymentDetail',
        ),
    ]
