# Generated by Django 3.2.9 on 2021-11-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0004_rename_paymentdetails_paymentdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='MID',
        ),
        migrations.AlterField(
            model_name='placedorder',
            name='order_status',
            field=models.CharField(choices=[('u', 'Payment Not Done'), ('f', 'Payment Failed'), ('s', 'Success'), ('w', 'Payment withdrawn'), ('i', 'Incomplete Payment')], default='u', max_length=1),
        ),
    ]
